#!/bin/bash
#SBATCH --partition=fast
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=5GB
#SBATCH -c 1
#SBATCH -t 24:00:00


module purge
module load nextflow/23.10.1 


PIPELINE="/shared/projects/microbiote_pdacrna/MicrobioteRNApipe/NextflowPipeline/main_microbiote_pipeline.nf"
CONFIG="/shared/projects/microbiote_pdacrna/MicrobioteRNApipe/NextflowPipeline/test.config"

## Adjust this command by keeping or removing the -resume option
nextflow -C ${CONFIG} run ${PIPELINE} -resume